Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import daggerml.executor as dx

def foo(fndag):
  import torch
  n = fndag.expr[1].value()
  fndag.commit(torch.arange(n).tolist())

lx = dx.Local()
fn = lx.make_fn(dag, foo, 'conda', 'torch')
resp = lx.run(dag, fn, 5)
resp.get_result().value()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mError[0m                                     Traceback (most recent call last)
Cell [0;32mIn[14], line 10[0m
[1;32m      8[0m lx [38;5;241m=[39m dx[38;5;241m.[39mLocal()
[1;32m      9[0m fn [38;5;241m=[39m lx[38;5;241m.[39mmake_fn(dag, foo, [38;5;124m'[39m[38;5;124mconda[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mtorch[39m[38;5;124m'[39m)
[0;32m---> 10[0m resp [38;5;241m=[39m [43mlx[49m[38;5;241;43m.[39;49m[43mrun[49m[43m([49m[43mdag[49m[43m,[49m[43m [49m[43mfn[49m[43m,[49m[43m [49m[38;5;241;43m5[39;49m[43m)[49m
[1;32m     11[0m resp[38;5;241m.[39mget_result()[38;5;241m.[39mvalue()

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/daggerml/executor.py:566[0m, in [0;36mLocal.run[0;34m(self, dag, fn_rsrc, *args)[0m
[1;32m    564[0m         [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_submit_remote(dump[38;5;241m=[39mdump, [38;5;241m*[39m[38;5;241m*[39mdata)
[1;32m    565[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_submit_local(dump[38;5;241m=[39mdump, [38;5;241m*[39m[38;5;241m*[39mdata)
[0;32m--> 566[0m [38;5;28;01mreturn[39;00m [43mdml[49m[38;5;241;43m.[39;49m[43mFnUpdater[49m[38;5;241;43m.[39;49m[43mfrom_waiter[49m[43m([49m[43mdag[49m[38;5;241;43m.[39;49m[43mstart_fn[49m[43m([49m[43mfn_rsrc[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[43margs[49m[43m)[49m[43m,[49m[43m [49m[43mupdate_fn[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/daggerml/core.py:137[0m, in [0;36mFnUpdater.from_waiter[0;34m(cls, waiter, update_fn)[0m
[1;32m    135[0m f [38;5;241m=[39m {k[38;5;241m.[39mname: [38;5;28mgetattr[39m(waiter, k[38;5;241m.[39mname) [38;5;28;01mfor[39;00m k [38;5;129;01min[39;00m fields(waiter)}
[1;32m    136[0m out [38;5;241m=[39m [38;5;28mcls[39m(update_fn[38;5;241m=[39mupdate_fn, [38;5;241m*[39m[38;5;241m*[39mf)
[0;32m--> 137[0m [43mout[49m[38;5;241;43m.[39;49m[43mupdate[49m[43m([49m[43m)[49m
[1;32m    138[0m [38;5;28;01mreturn[39;00m out

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/daggerml/core.py:153[0m, in [0;36mFnUpdater.update[0;34m(self)[0m
[1;32m    151[0m     dag [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mdag[38;5;241m.[39mapi[38;5;241m.[39mnew_dag([38;5;124m'[39m[38;5;124masdf[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mqwer[39m[38;5;124m'[39m, dump[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mdump)
[1;32m    152[0m     dag[38;5;241m.[39mcommit(Error[38;5;241m.[39mfrom_ex(e))
[0;32m--> 153[0m [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mget_result[49m[43m([49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/daggerml/core.py:121[0m, in [0;36mFnWaiter.get_result[0;34m(self)[0m
[1;32m    120[0m [38;5;28;01mdef[39;00m [38;5;21mget_result[39m([38;5;28mself[39m):
[0;32m--> 121[0m     ref [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mdag[49m[38;5;241;43m.[39;49m[43m_invoke[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mget_fn_result[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mref[49m[43m)[49m
[1;32m    122[0m     [38;5;28;01mif[39;00m ref [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[1;32m    123[0m         [38;5;28;01mreturn[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/daggerml/core.py:587[0m, in [0;36mDag._invoke[0;34m(self, op, *args, **kwargs)[0m
[1;32m    585[0m data [38;5;241m=[39m from_json(resp)
[1;32m    586[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(data, Error):
[0;32m--> 587[0m     [38;5;28;01mraise[39;00m data
[1;32m    588[0m [38;5;28;01mreturn[39;00m data

[0;31mError[0m: dml.Error(failed_local_execution: 'local command failed')

